{% set version = "5.5.1" %}

package:
  name: social-auth-app-django
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/social-auth-app-django/social_auth_app_django-{{ version }}.tar.gz
  sha256: a1435c17227d07d690b06cca54ea47d4ed939de4749dac45dd4393c8a98dac17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django
    - social-auth-core >=4.1.0

test:
  imports:
    - social_django
    - social_django.management
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python-social-auth/social-app-django
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python Social Authentication, Django integration.

extra:
  recipe-maintainers:
    - ocefpaf
