{% set python_min = "3.10" %}
{% set name = "social-auth-app-django" %}
{% set version = "5.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/social_auth_app_django-{{ version }}.tar.gz
  sha256: a1435c17227d07d690b06cca54ea47d4ed939de4749dac45dd4393c8a98dac17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=78.0.2
    - pip
  run:
    - python >={{ python_min }}
    - django >=5.1
    - social-auth-core >=4.4,<5.dev0

test:
  imports:
    - social_django
    - social_django.management
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python-social-auth/social-app-django
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python Social Authentication, Django integration.

extra:
  recipe-maintainers:
    - ocefpaf
