{% set version = "5.4.1" %}

package:
  name: social-auth-app-django
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/social-auth-app-django/social-auth-app-django-{{ version }}.tar.gz
  sha256: 2a43cde559dd34fdc7132417b6c52c780fa99ec2332dee9f405b4763f371c367

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django
    - social-auth-core >=4.1.0

test:
  imports:
    - social_django
    - social_django.management
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-social-auth/social-app-django
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python Social Authentication, Django integration.

extra:
  recipe-maintainers:
    - ocefpaf
